'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.5485
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("AccControlsWinForms.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property Accept_24x24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Accept_24x24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property buttonToolTipDefaultModifiers() As System.CodeDom.MemberAttributes
            Get
                Dim obj As Object = ResourceManager.GetObject("buttonToolTipDefaultModifiers", resourceCulture)
                Return CType(obj,System.CodeDom.MemberAttributes)
            End Get
        End Property
        
        Friend ReadOnly Property buttonToolTipLocation() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("buttonToolTipLocation", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        Friend ReadOnly Property buttonToolTipModifiers() As System.CodeDom.MemberAttributes
            Get
                Dim obj As Object = ResourceManager.GetObject("buttonToolTipModifiers", resourceCulture)
                Return CType(obj,System.CodeDom.MemberAttributes)
            End Get
        End Property
        
        Friend ReadOnly Property Cancel_24x24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Cancel_24x24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property chbSaveResponseDefaultModifiers() As System.CodeDom.MemberAttributes
            Get
                Dim obj As Object = ResourceManager.GetObject("chbSaveResponseDefaultModifiers", resourceCulture)
                Return CType(obj,System.CodeDom.MemberAttributes)
            End Get
        End Property
        
        Friend ReadOnly Property chbSaveResponseLocked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("chbSaveResponseLocked", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        Friend ReadOnly Property chbSaveResponseModifiers() As System.CodeDom.MemberAttributes
            Get
                Dim obj As Object = ResourceManager.GetObject("chbSaveResponseModifiers", resourceCulture)
                Return CType(obj,System.CodeDom.MemberAttributes)
            End Get
        End Property
        
        Friend ReadOnly Property csv_text() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("csv_text", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Error_red_16x16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Error_red_16x16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property error_red_32x32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("error_red_32x32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property excel() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("excel", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Flameia_Xrabbit_Device_Network() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("Flameia_Xrabbit_Device_Network", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property Flameia_Xrabbit_General_Private() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("Flameia_Xrabbit_General_Private", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property Flameia_Xrabbit_Tools_Activity_Monitor() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("Flameia_Xrabbit_Tools_Activity_Monitor", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property gears() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("gears", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property imageListIconsDefaultModifiers() As System.CodeDom.MemberAttributes
            Get
                Dim obj As Object = ResourceManager.GetObject("imageListIconsDefaultModifiers", resourceCulture)
                Return CType(obj,System.CodeDom.MemberAttributes)
            End Get
        End Property
        
        Friend ReadOnly Property imageListIconsImageStream() As System.Windows.Forms.ImageListStreamer
            Get
                Dim obj As Object = ResourceManager.GetObject("imageListIconsImageStream", resourceCulture)
                Return CType(obj,System.Windows.Forms.ImageListStreamer)
            End Get
        End Property
        
        Friend ReadOnly Property imageListIconsLocation() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("imageListIconsLocation", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        Friend ReadOnly Property imageListIconsModifiers() As System.CodeDom.MemberAttributes
            Get
                Dim obj As Object = ResourceManager.GetObject("imageListIconsModifiers", resourceCulture)
                Return CType(obj,System.CodeDom.MemberAttributes)
            End Get
        End Property
        
        Friend ReadOnly Property Information_6227_32x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Information_6227_32x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Information_blue_6227_16x16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Information_blue_6227_16x16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property InformationIco16() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("InformationIco16", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property panelIconDefaultModifiers() As System.CodeDom.MemberAttributes
            Get
                Dim obj As Object = ResourceManager.GetObject("panelIconDefaultModifiers", resourceCulture)
                Return CType(obj,System.CodeDom.MemberAttributes)
            End Get
        End Property
        
        Friend ReadOnly Property panelIconDrawGrid() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("panelIconDrawGrid", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        Friend ReadOnly Property panelIconGridSize() As System.Drawing.Size
            Get
                Dim obj As Object = ResourceManager.GetObject("panelIconGridSize", resourceCulture)
                Return CType(obj,System.Drawing.Size)
            End Get
        End Property
        
        Friend ReadOnly Property panelIconLocked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("panelIconLocked", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        Friend ReadOnly Property panelIconModifiers() As System.CodeDom.MemberAttributes
            Get
                Dim obj As Object = ResourceManager.GetObject("panelIconModifiers", resourceCulture)
                Return CType(obj,System.CodeDom.MemberAttributes)
            End Get
        End Property
        
        Friend ReadOnly Property panelIconSnapToGrid() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("panelIconSnapToGrid", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        Friend ReadOnly Property Paste_icon_16p() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Paste_icon_16p", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property PlusMinus_18x18() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PlusMinus_18x18", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property rtbMessageDefaultModifiers() As System.CodeDom.MemberAttributes
            Get
                Dim obj As Object = ResourceManager.GetObject("rtbMessageDefaultModifiers", resourceCulture)
                Return CType(obj,System.CodeDom.MemberAttributes)
            End Get
        End Property
        
        Friend ReadOnly Property rtbMessageLocked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("rtbMessageLocked", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        Friend ReadOnly Property rtbMessageModifiers() As System.CodeDom.MemberAttributes
            Get
                Dim obj As Object = ResourceManager.GetObject("rtbMessageModifiers", resourceCulture)
                Return CType(obj,System.CodeDom.MemberAttributes)
            End Get
        End Property
        
        Friend ReadOnly Property text_html() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("text_html", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Warning_yellow_7231_16x16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Warning_yellow_7231_16x16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property warning_yellow_7231_32x32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("warning_yellow_7231_32x32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property WarningIco16() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("WarningIco16", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
    End Module
End Namespace
