'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.5485
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System.Xml.Serialization

Namespace ActiveReports.Declarations.ISafTemplates.ISaf_1_2

    '
    'This source code was auto-generated by xsd, Version=2.0.50727.3038.
    '

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038"),
     System.SerializableAttribute(),
     System.Diagnostics.DebuggerStepThroughAttribute(),
     System.ComponentModel.DesignerCategoryAttribute("code"),
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.vmi.lt/cms/imas/isaf"),
     System.Xml.Serialization.XmlRootAttribute([Namespace]:="http://www.vmi.lt/cms/imas/isaf", IsNullable:=False)>
    Partial Public Class iSAFFile

        Private headerField As Header

        Private masterFilesField As MasterFiles

        Private sourceDocumentsField As SourceDocuments

        '''<remarks/>
        Public Property Header() As Header
            Get
                Return Me.headerField
            End Get
            Set(ByVal value As Header)
                Me.headerField = value
            End Set
        End Property

        '''<remarks/>
        Public Property MasterFiles() As MasterFiles
            Get
                Return Me.masterFilesField
            End Get
            Set(ByVal value As MasterFiles)
                Me.masterFilesField = value
            End Set
        End Property

        '''<remarks/>
        Public Property SourceDocuments() As SourceDocuments
            Get
                Return Me.sourceDocumentsField
            End Get
            Set(ByVal value As SourceDocuments)
                Me.sourceDocumentsField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038"),
     System.SerializableAttribute(),
     System.Diagnostics.DebuggerStepThroughAttribute(),
     System.ComponentModel.DesignerCategoryAttribute("code"),
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.vmi.lt/cms/imas/isaf")>
    Partial Public Class Header

        Private fileDescriptionField As FileDescription

        '''<remarks/>
        Public Property FileDescription() As FileDescription
            Get
                Return Me.fileDescriptionField
            End Get
            Set(ByVal value As FileDescription)
                Me.fileDescriptionField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038"),
     System.SerializableAttribute(),
     System.Diagnostics.DebuggerStepThroughAttribute(),
     System.ComponentModel.DesignerCategoryAttribute("code"),
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.vmi.lt/cms/imas/isaf")>
    Partial Public Class FileDescription

        Private fileVersionField As ISAFFileVersion

        Private fileDateCreatedField As Date

        Private dataTypeField As ISAFDataType

        Private softwareCompanyNameField As String

        Private softwareNameField As String

        Private softwareVersionField As String

        Private registrationNumberField As ULong

        Private numberOfPartsField As System.Nullable(Of UInteger)

        Private partNumberField As String

        Private selectionCriteriaField As SelectionCriteria

        '''<remarks/>
        Public Property FileVersion() As ISAFFileVersion
            Get
                Return Me.fileVersionField
            End Get
            Set(ByVal value As ISAFFileVersion)
                Me.fileVersionField = value
            End Set
        End Property

        '''<remarks/>
        Public Property FileDateCreated() As Date
            Get
                Return Me.fileDateCreatedField
            End Get
            Set(ByVal value As Date)
                Me.fileDateCreatedField = value
            End Set
        End Property

        '''<remarks/>
        Public Property DataType() As ISAFDataType
            Get
                Return Me.dataTypeField
            End Get
            Set(ByVal value As ISAFDataType)
                Me.dataTypeField = value
            End Set
        End Property

        '''<remarks/>
        Public Property SoftwareCompanyName() As String
            Get
                Return Me.softwareCompanyNameField
            End Get
            Set(ByVal value As String)
                Me.softwareCompanyNameField = value
            End Set
        End Property

        '''<remarks/>
        Public Property SoftwareName() As String
            Get
                Return Me.softwareNameField
            End Get
            Set(ByVal value As String)
                Me.softwareNameField = value
            End Set
        End Property

        '''<remarks/>
        Public Property SoftwareVersion() As String
            Get
                Return Me.softwareVersionField
            End Get
            Set(ByVal value As String)
                Me.softwareVersionField = value
            End Set
        End Property

        '''<remarks/>
        Public Property RegistrationNumber() As ULong
            Get
                Return Me.registrationNumberField
            End Get
            Set(ByVal value As ULong)
                Me.registrationNumberField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=True)>
        Public Property NumberOfParts() As System.Nullable(Of UInteger)
            Get
                Return Me.numberOfPartsField
            End Get
            Set(ByVal value As System.Nullable(Of UInteger))
                Me.numberOfPartsField = value
            End Set
        End Property

        '''<remarks/>
        Public Property PartNumber() As String
            Get
                Return Me.partNumberField
            End Get
            Set(ByVal value As String)
                Me.partNumberField = value
            End Set
        End Property

        '''<remarks/>
        Public Property SelectionCriteria() As SelectionCriteria
            Get
                Return Me.selectionCriteriaField
            End Get
            Set(ByVal value As SelectionCriteria)
                Me.selectionCriteriaField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038"),
     System.SerializableAttribute(),
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.vmi.lt/cms/imas/isaf")>
    Public Enum ISAFFileVersion

        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("iSAF1.2")>
        iSAF12

    End Enum

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038"),
     System.SerializableAttribute(),
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.vmi.lt/cms/imas/isaf")>
    Public Enum ISAFDataType

        '''<remarks/>
        F

        '''<remarks/>
        S

        '''<remarks/>
        P
    End Enum

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038"),
     System.SerializableAttribute(),
     System.Diagnostics.DebuggerStepThroughAttribute(),
     System.ComponentModel.DesignerCategoryAttribute("code"),
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.vmi.lt/cms/imas/isaf")>
    Partial Public Class SelectionCriteria

        Private selectionStartDateField As Date

        Private selectionEndDateField As Date

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="date")>
        Public Property SelectionStartDate() As Date
            Get
                Return Me.selectionStartDateField
            End Get
            Set(ByVal value As Date)
                Me.selectionStartDateField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="date")>
        Public Property SelectionEndDate() As Date
            Get
                Return Me.selectionEndDateField
            End Get
            Set(ByVal value As Date)
                Me.selectionEndDateField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038"),
     System.SerializableAttribute(),
     System.Diagnostics.DebuggerStepThroughAttribute(),
     System.ComponentModel.DesignerCategoryAttribute("code"),
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.vmi.lt/cms/imas/isaf")>
    Partial Public Class ReferenceToInvoice

        Private invoiceNoField As String

        Private invoiceDateField As Date

        Private amountField As Decimal

        Private vATAmountField As Decimal

        '''<remarks/>
        Public Property InvoiceNo() As String
            Get
                Return Me.invoiceNoField
            End Get
            Set(ByVal value As String)
                Me.invoiceNoField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="date")>
        Public Property InvoiceDate() As Date
            Get
                Return Me.invoiceDateField
            End Get
            Set(ByVal value As Date)
                Me.invoiceDateField = value
            End Set
        End Property

        '''<remarks/>
        Public Property Amount() As Decimal
            Get
                Return Me.amountField
            End Get
            Set(ByVal value As Decimal)
                Me.amountField = value
            End Set
        End Property

        '''<remarks/>
        Public Property VATAmount() As Decimal
            Get
                Return Me.vATAmountField
            End Get
            Set(ByVal value As Decimal)
                Me.vATAmountField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038"),
     System.SerializableAttribute(),
     System.Diagnostics.DebuggerStepThroughAttribute(),
     System.ComponentModel.DesignerCategoryAttribute("code"),
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.vmi.lt/cms/imas/isaf")>
    Partial Public Class Payment

        Private supplierCustomerIDField As String

        Private vATRegistrationNumberField As String

        Private registrationNumberField As String

        Private countryField As String

        Private nameField As String

        '''<remarks/>
        Public Property SupplierCustomerID() As String
            Get
                Return Me.supplierCustomerIDField
            End Get
            Set(ByVal value As String)
                Me.supplierCustomerIDField = value
            End Set
        End Property

        '''<remarks/>
        Public Property VATRegistrationNumber() As String
            Get
                Return Me.vATRegistrationNumberField
            End Get
            Set(ByVal value As String)
                Me.vATRegistrationNumberField = value
            End Set
        End Property

        '''<remarks/>
        Public Property RegistrationNumber() As String
            Get
                Return Me.registrationNumberField
            End Get
            Set(ByVal value As String)
                Me.registrationNumberField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=True)>
        Public Property Country() As String
            Get
                Return Me.countryField
            End Get
            Set(ByVal value As String)
                Me.countryField = value
            End Set
        End Property

        '''<remarks/>
        Public Property Name() As String
            Get
                Return Me.nameField
            End Get
            Set(ByVal value As String)
                Me.nameField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038"),
     System.SerializableAttribute(),
     System.Diagnostics.DebuggerStepThroughAttribute(),
     System.ComponentModel.DesignerCategoryAttribute("code"),
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.vmi.lt/cms/imas/isaf")>
    Partial Public Class SettlementAndPayment

        Private settlementTypeField As ISAFshorttext1Type

        Private settlementRefNoField As String

        Private settlementDateField As Date

        Private paymentField As Payment

        Private referencesToInvoiceField() As ReferenceToInvoice

        '''<remarks/>
        Public Property SettlementType() As ISAFshorttext1Type
            Get
                Return Me.settlementTypeField
            End Get
            Set(ByVal value As ISAFshorttext1Type)
                Me.settlementTypeField = value
            End Set
        End Property

        '''<remarks/>
        Public Property SettlementRefNo() As String
            Get
                Return Me.settlementRefNoField
            End Get
            Set(ByVal value As String)
                Me.settlementRefNoField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="date")>
        Public Property SettlementDate() As Date
            Get
                Return Me.settlementDateField
            End Get
            Set(ByVal value As Date)
                Me.settlementDateField = value
            End Set
        End Property

        '''<remarks/>
        Public Property Payment() As Payment
            Get
                Return Me.paymentField
            End Get
            Set(ByVal value As Payment)
                Me.paymentField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute(IsNullable:=False)>
        Public Property ReferencesToInvoice() As ReferenceToInvoice()
            Get
                Return Me.referencesToInvoiceField
            End Get
            Set(ByVal value As ReferenceToInvoice())
                Me.referencesToInvoiceField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038"),
     System.SerializableAttribute(),
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.vmi.lt/cms/imas/isaf")>
    Public Enum ISAFshorttext1Type

        '''<remarks/>
        G

        '''<remarks/>
        V
    End Enum

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038"),
     System.SerializableAttribute(),
     System.Diagnostics.DebuggerStepThroughAttribute(),
     System.ComponentModel.DesignerCategoryAttribute("code"),
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.vmi.lt/cms/imas/isaf")>
    Partial Public Class SalesDocumentTotal

        Private taxableValueField As Decimal

        Private taxCodeField As String

        Private taxPercentageField As System.Nullable(Of Decimal)

        Private amountField As System.Nullable(Of Decimal)

        Private vATPointDate2Field As System.Nullable(Of Date)

        '''<remarks/>
        Public Property TaxableValue() As Decimal
            Get
                Return Me.taxableValueField
            End Get
            Set(ByVal value As Decimal)
                Me.taxableValueField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=True)>
        Public Property TaxCode() As String
            Get
                Return Me.taxCodeField
            End Get
            Set(ByVal value As String)
                Me.taxCodeField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=True)>
        Public Property TaxPercentage() As System.Nullable(Of Decimal)
            Get
                Return Me.taxPercentageField
            End Get
            Set(ByVal value As System.Nullable(Of Decimal))
                Me.taxPercentageField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=True)>
        Public Property Amount() As System.Nullable(Of Decimal)
            Get
                Return Me.amountField
            End Get
            Set(ByVal value As System.Nullable(Of Decimal))
                Me.amountField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="date", IsNullable:=True)>
        Public Property VATPointDate2() As System.Nullable(Of Date)
            Get
                Return Me.vATPointDate2Field
            End Get
            Set(ByVal value As System.Nullable(Of Date))
                Me.vATPointDate2Field = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038"),
     System.SerializableAttribute(),
     System.Diagnostics.DebuggerStepThroughAttribute(),
     System.ComponentModel.DesignerCategoryAttribute("code"),
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.vmi.lt/cms/imas/isaf")>
    Partial Public Class CustomerInfo

        Private customerIDField As String

        Private vATRegistrationNumberField As String

        Private registrationNumberField As String

        Private countryField As String

        Private nameField As String

        '''<remarks/>
        Public Property CustomerID() As String
            Get
                Return Me.customerIDField
            End Get
            Set(ByVal value As String)
                Me.customerIDField = value
            End Set
        End Property

        '''<remarks/>
        Public Property VATRegistrationNumber() As String
            Get
                Return Me.vATRegistrationNumberField
            End Get
            Set(ByVal value As String)
                Me.vATRegistrationNumberField = value
            End Set
        End Property

        '''<remarks/>
        Public Property RegistrationNumber() As String
            Get
                Return Me.registrationNumberField
            End Get
            Set(ByVal value As String)
                Me.registrationNumberField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=True)>
        Public Property Country() As String
            Get
                Return Me.countryField
            End Get
            Set(ByVal value As String)
                Me.countryField = value
            End Set
        End Property

        '''<remarks/>
        Public Property Name() As String
            Get
                Return Me.nameField
            End Get
            Set(ByVal value As String)
                Me.nameField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038"),
     System.SerializableAttribute(),
     System.Diagnostics.DebuggerStepThroughAttribute(),
     System.ComponentModel.DesignerCategoryAttribute("code"),
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.vmi.lt/cms/imas/isaf")>
    Partial Public Class SalesInvoice

        Private invoiceNoField As String

        Private customerInfoField As CustomerInfo

        Private invoiceDateField As Date

        Private invoiceTypeField As ISAFshorttext2Type

        Private specialTaxationField As ISAFSpecialTaxationType

        Private referencesField() As Reference

        Private vATPointDateField As System.Nullable(Of Date)

        Private documentTotalsField() As SalesDocumentTotal

        '''<remarks/>
        Public Property InvoiceNo() As String
            Get
                Return Me.invoiceNoField
            End Get
            Set(ByVal value As String)
                Me.invoiceNoField = value
            End Set
        End Property

        '''<remarks/>
        Public Property CustomerInfo() As CustomerInfo
            Get
                Return Me.customerInfoField
            End Get
            Set(ByVal value As CustomerInfo)
                Me.customerInfoField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="date")>
        Public Property InvoiceDate() As Date
            Get
                Return Me.invoiceDateField
            End Get
            Set(ByVal value As Date)
                Me.invoiceDateField = value
            End Set
        End Property

        '''<remarks/>
        Public Property InvoiceType() As ISAFshorttext2Type
            Get
                Return Me.invoiceTypeField
            End Get
            Set(ByVal value As ISAFshorttext2Type)
                Me.invoiceTypeField = value
            End Set
        End Property

        '''<remarks/>
        Public Property SpecialTaxation() As ISAFSpecialTaxationType
            Get
                Return Me.specialTaxationField
            End Get
            Set(ByVal value As ISAFSpecialTaxationType)
                Me.specialTaxationField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute(IsNullable:=False)>
        Public Property References() As Reference()
            Get
                Return Me.referencesField
            End Get
            Set(ByVal value As Reference())
                Me.referencesField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="date", IsNullable:=True)>
        Public Property VATPointDate() As System.Nullable(Of Date)
            Get
                Return Me.vATPointDateField
            End Get
            Set(ByVal value As System.Nullable(Of Date))
                Me.vATPointDateField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute("DocumentTotal", IsNullable:=False)>
        Public Property DocumentTotals() As SalesDocumentTotal()
            Get
                Return Me.documentTotalsField
            End Get
            Set(ByVal value As SalesDocumentTotal())
                Me.documentTotalsField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038"),
     System.SerializableAttribute(),
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.vmi.lt/cms/imas/isaf")>
    Public Enum ISAFshorttext2Type

        '''<remarks/>
        SF

        '''<remarks/>
        DS

        '''<remarks/>
        KS

        '''<remarks/>
        VS

        '''<remarks/>
        VD

        '''<remarks/>
        VK

        '''<remarks/>
        AN

        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("")>
        Item
    End Enum

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038"),
     System.SerializableAttribute(),
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.vmi.lt/cms/imas/isaf")>
    Public Enum ISAFSpecialTaxationType

        '''<remarks/>
        T

        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("")>
        Item
    End Enum

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038"),
     System.SerializableAttribute(),
     System.Diagnostics.DebuggerStepThroughAttribute(),
     System.ComponentModel.DesignerCategoryAttribute("code"),
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.vmi.lt/cms/imas/isaf")>
    Partial Public Class Reference

        Private referenceNoField As String

        Private referenceDateField As Date

        '''<remarks/>
        Public Property ReferenceNo() As String
            Get
                Return Me.referenceNoField
            End Get
            Set(ByVal value As String)
                Me.referenceNoField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="date")>
        Public Property ReferenceDate() As Date
            Get
                Return Me.referenceDateField
            End Get
            Set(ByVal value As Date)
                Me.referenceDateField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038"),
     System.SerializableAttribute(),
     System.Diagnostics.DebuggerStepThroughAttribute(),
     System.ComponentModel.DesignerCategoryAttribute("code"),
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.vmi.lt/cms/imas/isaf")>
    Partial Public Class PurchaseDocumentTotal

        Private taxableValueField As Decimal

        Private taxCodeField As String

        Private taxPercentageField As System.Nullable(Of Decimal)

        Private amountField As System.Nullable(Of Decimal)

        '''<remarks/>
        Public Property TaxableValue() As Decimal
            Get
                Return Me.taxableValueField
            End Get
            Set(ByVal value As Decimal)
                Me.taxableValueField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=True)>
        Public Property TaxCode() As String
            Get
                Return Me.taxCodeField
            End Get
            Set(ByVal value As String)
                Me.taxCodeField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=True)>
        Public Property TaxPercentage() As System.Nullable(Of Decimal)
            Get
                Return Me.taxPercentageField
            End Get
            Set(ByVal value As System.Nullable(Of Decimal))
                Me.taxPercentageField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=True)>
        Public Property Amount() As System.Nullable(Of Decimal)
            Get
                Return Me.amountField
            End Get
            Set(ByVal value As System.Nullable(Of Decimal))
                Me.amountField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038"),
     System.SerializableAttribute(),
     System.Diagnostics.DebuggerStepThroughAttribute(),
     System.ComponentModel.DesignerCategoryAttribute("code"),
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.vmi.lt/cms/imas/isaf")>
    Partial Public Class SupplierInfo

        Private supplierIDField As String

        Private vATRegistrationNumberField As String

        Private registrationNumberField As String

        Private countryField As String

        Private nameField As String

        '''<remarks/>
        Public Property SupplierID() As String
            Get
                Return Me.supplierIDField
            End Get
            Set(ByVal value As String)
                Me.supplierIDField = value
            End Set
        End Property

        '''<remarks/>
        Public Property VATRegistrationNumber() As String
            Get
                Return Me.vATRegistrationNumberField
            End Get
            Set(ByVal value As String)
                Me.vATRegistrationNumberField = value
            End Set
        End Property

        '''<remarks/>
        Public Property RegistrationNumber() As String
            Get
                Return Me.registrationNumberField
            End Get
            Set(ByVal value As String)
                Me.registrationNumberField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=True)>
        Public Property Country() As String
            Get
                Return Me.countryField
            End Get
            Set(ByVal value As String)
                Me.countryField = value
            End Set
        End Property

        '''<remarks/>
        Public Property Name() As String
            Get
                Return Me.nameField
            End Get
            Set(ByVal value As String)
                Me.nameField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038"),
     System.SerializableAttribute(),
     System.Diagnostics.DebuggerStepThroughAttribute(),
     System.ComponentModel.DesignerCategoryAttribute("code"),
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.vmi.lt/cms/imas/isaf")>
    Partial Public Class PurchaseInvoice

        Private invoiceNoField As String

        Private supplierInfoField As SupplierInfo

        Private invoiceDateField As Date

        Private invoiceTypeField As ISAFshorttext2Type

        Private specialTaxationField As ISAFSpecialTaxationType

        Private referencesField() As Reference

        Private vATPointDateField As System.Nullable(Of Date)

        Private registrationAccountDateField As System.Nullable(Of Date)

        Private documentTotalsField() As PurchaseDocumentTotal

        '''<remarks/>
        Public Property InvoiceNo() As String
            Get
                Return Me.invoiceNoField
            End Get
            Set(ByVal value As String)
                Me.invoiceNoField = value
            End Set
        End Property

        '''<remarks/>
        Public Property SupplierInfo() As SupplierInfo
            Get
                Return Me.supplierInfoField
            End Get
            Set(ByVal value As SupplierInfo)
                Me.supplierInfoField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="date")>
        Public Property InvoiceDate() As Date
            Get
                Return Me.invoiceDateField
            End Get
            Set(ByVal value As Date)
                Me.invoiceDateField = value
            End Set
        End Property

        '''<remarks/>
        Public Property InvoiceType() As ISAFshorttext2Type
            Get
                Return Me.invoiceTypeField
            End Get
            Set(ByVal value As ISAFshorttext2Type)
                Me.invoiceTypeField = value
            End Set
        End Property

        '''<remarks/>
        Public Property SpecialTaxation() As ISAFSpecialTaxationType
            Get
                Return Me.specialTaxationField
            End Get
            Set(ByVal value As ISAFSpecialTaxationType)
                Me.specialTaxationField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute(IsNullable:=False)>
        Public Property References() As Reference()
            Get
                Return Me.referencesField
            End Get
            Set(ByVal value As Reference())
                Me.referencesField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="date", IsNullable:=True)>
        Public Property VATPointDate() As System.Nullable(Of Date)
            Get
                Return Me.vATPointDateField
            End Get
            Set(ByVal value As System.Nullable(Of Date))
                Me.vATPointDateField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="date", IsNullable:=True)>
        Public Property RegistrationAccountDate() As System.Nullable(Of Date)
            Get
                Return Me.registrationAccountDateField
            End Get
            Set(ByVal value As System.Nullable(Of Date))
                Me.registrationAccountDateField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute("DocumentTotal", IsNullable:=False)>
        Public Property DocumentTotals() As PurchaseDocumentTotal()
            Get
                Return Me.documentTotalsField
            End Get
            Set(ByVal value As PurchaseDocumentTotal())
                Me.documentTotalsField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038"),
     System.SerializableAttribute(),
     System.Diagnostics.DebuggerStepThroughAttribute(),
     System.ComponentModel.DesignerCategoryAttribute("code"),
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.vmi.lt/cms/imas/isaf")>
    Partial Public Class SourceDocuments

        Private purchaseInvoicesField() As PurchaseInvoice

        Private salesInvoicesField() As SalesInvoice

        Private settlementsAndPaymentsField() As SettlementAndPayment

        '''<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute("Invoice", IsNullable:=False)>
        Public Property PurchaseInvoices() As PurchaseInvoice()
            Get
                Return Me.purchaseInvoicesField
            End Get
            Set(ByVal value As PurchaseInvoice())
                Me.purchaseInvoicesField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute("Invoice", IsNullable:=False)>
        Public Property SalesInvoices() As SalesInvoice()
            Get
                Return Me.salesInvoicesField
            End Get
            Set(ByVal value As SalesInvoice())
                Me.salesInvoicesField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute(IsNullable:=False)>
        Public Property SettlementsAndPayments() As SettlementAndPayment()
            Get
                Return Me.settlementsAndPaymentsField
            End Get
            Set(ByVal value As SettlementAndPayment())
                Me.settlementsAndPaymentsField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038"),
     System.SerializableAttribute(),
     System.Diagnostics.DebuggerStepThroughAttribute(),
     System.ComponentModel.DesignerCategoryAttribute("code"),
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.vmi.lt/cms/imas/isaf")>
    Partial Public Class Supplier

        Private supplierIDField As String

        Private vATRegistrationNumberField As String

        Private registrationNumberField As String

        Private countryField As String

        Private nameField As String

        '''<remarks/>
        Public Property SupplierID() As String
            Get
                Return Me.supplierIDField
            End Get
            Set(ByVal value As String)
                Me.supplierIDField = value
            End Set
        End Property

        '''<remarks/>
        Public Property VATRegistrationNumber() As String
            Get
                Return Me.vATRegistrationNumberField
            End Get
            Set(ByVal value As String)
                Me.vATRegistrationNumberField = value
            End Set
        End Property

        '''<remarks/>
        Public Property RegistrationNumber() As String
            Get
                Return Me.registrationNumberField
            End Get
            Set(ByVal value As String)
                Me.registrationNumberField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=True)>
        Public Property Country() As String
            Get
                Return Me.countryField
            End Get
            Set(ByVal value As String)
                Me.countryField = value
            End Set
        End Property

        '''<remarks/>
        Public Property Name() As String
            Get
                Return Me.nameField
            End Get
            Set(ByVal value As String)
                Me.nameField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038"),
     System.SerializableAttribute(),
     System.Diagnostics.DebuggerStepThroughAttribute(),
     System.ComponentModel.DesignerCategoryAttribute("code"),
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.vmi.lt/cms/imas/isaf")>
    Partial Public Class Customer

        Private customerIDField As String

        Private vATRegistrationNumberField As String

        Private registrationNumberField As String

        Private countryField As String

        Private nameField As String

        '''<remarks/>
        Public Property CustomerID() As String
            Get
                Return Me.customerIDField
            End Get
            Set(ByVal value As String)
                Me.customerIDField = value
            End Set
        End Property

        '''<remarks/>
        Public Property VATRegistrationNumber() As String
            Get
                Return Me.vATRegistrationNumberField
            End Get
            Set(ByVal value As String)
                Me.vATRegistrationNumberField = value
            End Set
        End Property

        '''<remarks/>
        Public Property RegistrationNumber() As String
            Get
                Return Me.registrationNumberField
            End Get
            Set(ByVal value As String)
                Me.registrationNumberField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=True)>
        Public Property Country() As String
            Get
                Return Me.countryField
            End Get
            Set(ByVal value As String)
                Me.countryField = value
            End Set
        End Property

        '''<remarks/>
        Public Property Name() As String
            Get
                Return Me.nameField
            End Get
            Set(ByVal value As String)
                Me.nameField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038"),
     System.SerializableAttribute(),
     System.Diagnostics.DebuggerStepThroughAttribute(),
     System.ComponentModel.DesignerCategoryAttribute("code"),
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.vmi.lt/cms/imas/isaf")>
    Partial Public Class MasterFiles

        Private customersField() As Customer

        Private suppliersField() As Supplier

        '''<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute(IsNullable:=False)>
        Public Property Customers() As Customer()
            Get
                Return Me.customersField
            End Get
            Set(ByVal value As Customer())
                Me.customersField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute(IsNullable:=False)>
        Public Property Suppliers() As Supplier()
            Get
                Return Me.suppliersField
            End Get
            Set(ByVal value As Supplier())
                Me.suppliersField = value
            End Set
        End Property
    End Class

End Namespace
