'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3655
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("ApskaitaWUI.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property Action_file_new_icon_16p() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Action_file_new_icon_16p", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Action_file_new_icon_24p() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Action_file_new_icon_24p", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Action_file_new_icon_32p() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Action_file_new_icon_32p", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Action_file_new_icon_48p() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Action_file_new_icon_48p", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Action_lock_full_icon_16p() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Action_lock_full_icon_16p", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Action_lock_full_icon_24p() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Action_lock_full_icon_24p", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Action_lock_full_icon_32p() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Action_lock_full_icon_32p", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Action_lock_full_icon_48p() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Action_lock_full_icon_48p", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Action_lock_icon_16p() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Action_lock_icon_16p", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Action_lock_icon_24p() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Action_lock_icon_24p", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Action_lock_icon_32p() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Action_lock_icon_32p", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Action_lock_icon_48p() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Action_lock_icon_48p", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Actions_document_save_icon_16p() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Actions_document_save_icon_16p", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Actions_document_save_icon_24p() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Actions_document_save_icon_24p", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Actions_document_save_icon_32p() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Actions_document_save_icon_32p", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Actions_document_save_icon_48p() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Actions_document_save_icon_48p", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Actions_edit_copy_icon_16p() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Actions_edit_copy_icon_16p", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Actions_edit_copy_icon_24p() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Actions_edit_copy_icon_24p", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Actions_edit_copy_icon_32p() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Actions_edit_copy_icon_32p", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Actions_edit_copy_icon_48p() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Actions_edit_copy_icon_48p", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bill32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bill32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property books32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("books32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property booksadd32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("booksadd32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Button_Reload_icon_16p() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Button_Reload_icon_16p", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Button_Reload_icon_24p() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Button_Reload_icon_24p", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Button_Reload_icon_32p() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Button_Reload_icon_32p", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Button_Reload_icon_48p() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Button_Reload_icon_48p", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property calculator_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("calculator_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property calculator_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("calculator_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property calculator_48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("calculator_48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property database_refresh() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("database_refresh", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property database_save() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("database_save", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property database_search_icon_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("database_search_icon_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property database_search_icon_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("database_search_icon_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property database_search_icon_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("database_search_icon_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property database_search_icon_48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("database_search_icon_48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property database_settings_icon_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("database_settings_icon_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property database_settings_icon_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("database_settings_icon_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property database_settings_icon_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("database_settings_icon_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property database_settings_icon_48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("database_settings_icon_48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property eile32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("eile32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property email_send_receive_icon_16p() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("email_send_receive_icon_16p", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property email_send_receive_icon_24p() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("email_send_receive_icon_24p", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property email_send_receive_icon_32p() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("email_send_receive_icon_32p", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property eta32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("eta32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Excel_32x32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Excel_32x32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property filesaveas_16x16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("filesaveas_16x16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property filesaveas_22x22() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("filesaveas_22x22", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property filesaveas_24x24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("filesaveas_24x24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property filesaveas_32x32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("filesaveas_32x32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property folder_open_icon_16p() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("folder_open_icon_16p", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property folder_open_icon_24p() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("folder_open_icon_24p", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property folder_open_icon_32p() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("folder_open_icon_32p", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property folder_open_icon_48p() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("folder_open_icon_48p", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property FromFillerIcon_16x16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FromFillerIcon_16x16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property FromFillerIcon_24x24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FromFillerIcon_24x24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property FromFillerIcon_24x24alt() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FromFillerIcon_24x24alt", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property FromFillerIcon_32x32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FromFillerIcon_32x32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property FromFillerIcon_48x48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FromFillerIcon_48x48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property icon_eye() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icon_eye", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property isirasytisask32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("isirasytisask32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property lektuvelis_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("lektuvelis_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property lektuvelis_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("lektuvelis_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property lektuvelis_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("lektuvelis_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property lektuvelis_48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("lektuvelis_48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property link_go_icon_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("link_go_icon_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property link_go_icon_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("link_go_icon_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property link_go_icon_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("link_go_icon_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Veiklai naudojami nauji pastatai bei pastatų, įtrauktų į Lietuvos Respublikos nekilnojamųjų kultūros vertybių registrą, rekonstravimas
        '''
        '''8
        '''
        '''Gyvenamieji namai
        '''
        '''20
        '''
        '''Kiti aukščiau neišvardyti pastatai
        '''
        '''15
        '''
        '''Mašinos ir įrengimai
        '''
        '''5
        '''
        '''Įrenginiai (statiniai, gręžiniai ir kt.)
        '''
        '''8
        '''
        '''Elektros perdavimo ir ryšių įtaisai (išskyrus kompiuterinius tinklus)	 
        '''	 
        '''8
        '''
        '''Geležinkelio riedmenys (šilumvežiai, vagonai, cisternos), laivai	 
        '''	 
        '''8
        '''
        '''Vamzdynai, lėktuvai, ginklai
        '''
        '''15
        '''
        '''Baldai, išskyrus naudoj [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Nusidevejimas() As String
            Get
                Return ResourceManager.GetString("Nusidevejimas", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property open_document_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("open_document_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property open_document_22() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("open_document_22", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property orderis32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("orderis32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Paste_icon_16p() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Paste_icon_16p", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Paste_icon_24p() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Paste_icon_24p", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Paste_icon_32p() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Paste_icon_32p", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Paste_icon_48p() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Paste_icon_48p", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property pie32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pie32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property prekkat32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("prekkat32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property prekkatnew32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("prekkatnew32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property PreviewIcon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PreviewIcon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property prinprew32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("prinprew32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property printer() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("printer", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property printer32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("printer32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property PrintIcon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PrintIcon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property regsasfakt32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("regsasfakt32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property saskait32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("saskait32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property service32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("service32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property servicenew32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("servicenew32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 1	ILGALAIKIS TURTAS
        '''
        '''11	Nematerialusis turtas
        '''
        '''111	Plėtros darbai
        '''	1110 Įsigijimo savikaina
        '''	1118 Amortizacija (-)
        '''	1119 Vertės sumažėjimas (-)
        '''
        '''112	Prestižas
        '''	1120 Įsigijimo savikaina
        '''	1128 Amortizacija (-)
        '''	1129 Vertės sumažėjimas (-)
        '''
        '''113	Patentai, licencijos
        '''	1130 Įsigijimo savikaina
        '''	1138 Amortizacija (-)
        '''	1139 Vertės sumažėjimas (-)
        '''
        '''114	Programinė įranga
        '''	1140 Įsigijimo savikaina
        '''	1148 Amortizacija (-)
        '''	1149 Vertės sumažėjimas (-)
        '''
        '''115	Kitas nematerialusis turtas
        '''	1150 Įsigij [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property SP() As String
            Get
                Return ResourceManager.GetString("SP", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property sql_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sql_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property sql_20() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sql_20", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property sql_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sql_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property sql_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sql_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property sql_48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sql_48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property sqlquery_16x16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sqlquery_16x16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property users32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("users32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property usersadd32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("usersadd32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Web_Database_icon_16p() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Web_Database_icon_16p", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Web_Database_icon_24p() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Web_Database_icon_24p", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Web_Database_icon_32p() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Web_Database_icon_32p", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Web_Database_icon_48p() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Web_Database_icon_48p", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property zalsva_maza() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("zalsva_maza", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
    End Module
End Namespace
