'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.5485
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("AccCommon.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Klaida. Kalbos kodas {0} neatitinka nė vieno ISO 639-1 standarto kodo..
        '''</summary>
        Friend ReadOnly Property Common_InvalidLanguageCode() As String
            Get
                Return ResourceManager.GetString("Common_InvalidLanguageCode", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Klaida. Kalba, kurios pavadinimas yra {0}, nežinoma..
        '''</summary>
        Friend ReadOnly Property Common_InvalidLanguageName() As String
            Get
                Return ResourceManager.GetString("Common_InvalidLanguageName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Klaida. Kalbos kodui {0} nerastas pavadinimas (kultūra - {1})..
        '''</summary>
        Friend ReadOnly Property Common_localizedLanguageNameMissing() As String
            Get
                Return ResourceManager.GetString("Common_localizedLanguageNameMissing", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Afarų kalba.
        '''</summary>
        Friend ReadOnly Property LanguageCode_aa() As String
            Get
                Return ResourceManager.GetString("LanguageCode_aa", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Abchazų kalba.
        '''</summary>
        Friend ReadOnly Property LanguageCode_ab() As String
            Get
                Return ResourceManager.GetString("LanguageCode_ab", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Avestos kalba.
        '''</summary>
        Friend ReadOnly Property LanguageCode_ae() As String
            Get
                Return ResourceManager.GetString("LanguageCode_ae", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Afrikanų kalba.
        '''</summary>
        Friend ReadOnly Property LanguageCode_af() As String
            Get
                Return ResourceManager.GetString("LanguageCode_af", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Akanų kalba.
        '''</summary>
        Friend ReadOnly Property LanguageCode_ak() As String
            Get
                Return ResourceManager.GetString("LanguageCode_ak", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Amherų kalba.
        '''</summary>
        Friend ReadOnly Property LanguageCode_am() As String
            Get
                Return ResourceManager.GetString("LanguageCode_am", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Aragoniečių kalba.
        '''</summary>
        Friend ReadOnly Property LanguageCode_an() As String
            Get
                Return ResourceManager.GetString("LanguageCode_an", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Arabų kalba.
        '''</summary>
        Friend ReadOnly Property LanguageCode_ar() As String
            Get
                Return ResourceManager.GetString("LanguageCode_ar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Asamų kalba.
        '''</summary>
        Friend ReadOnly Property LanguageCode_as() As String
            Get
                Return ResourceManager.GetString("LanguageCode_as", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Avarų kalba.
        '''</summary>
        Friend ReadOnly Property LanguageCode_av() As String
            Get
                Return ResourceManager.GetString("LanguageCode_av", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Aimarų kalba.
        '''</summary>
        Friend ReadOnly Property LanguageCode_ay() As String
            Get
                Return ResourceManager.GetString("LanguageCode_ay", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Azerbaidžaniečių kalba.
        '''</summary>
        Friend ReadOnly Property LanguageCode_az() As String
            Get
                Return ResourceManager.GetString("LanguageCode_az", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Baškirų kalba.
        '''</summary>
        Friend ReadOnly Property LanguageCode_ba() As String
            Get
                Return ResourceManager.GetString("LanguageCode_ba", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Baltarusių kalba.
        '''</summary>
        Friend ReadOnly Property LanguageCode_be() As String
            Get
                Return ResourceManager.GetString("LanguageCode_be", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Bulgarų kalba.
        '''</summary>
        Friend ReadOnly Property LanguageCode_bg() As String
            Get
                Return ResourceManager.GetString("LanguageCode_bg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Biharų kalba.
        '''</summary>
        Friend ReadOnly Property LanguageCode_bh() As String
            Get
                Return ResourceManager.GetString("LanguageCode_bh", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Bislama.
        '''</summary>
        Friend ReadOnly Property LanguageCode_bi() As String
            Get
                Return ResourceManager.GetString("LanguageCode_bi", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Bambarų kalba.
        '''</summary>
        Friend ReadOnly Property LanguageCode_bm() As String
            Get
                Return ResourceManager.GetString("LanguageCode_bm", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Bengalų kalba.
        '''</summary>
        Friend ReadOnly Property LanguageCode_bn() As String
            Get
                Return ResourceManager.GetString("LanguageCode_bn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tibetiečių kalba.
        '''</summary>
        Friend ReadOnly Property LanguageCode_bo() As String
            Get
                Return ResourceManager.GetString("LanguageCode_bo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Bretonų kalba.
        '''</summary>
        Friend ReadOnly Property LanguageCode_br() As String
            Get
                Return ResourceManager.GetString("LanguageCode_br", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Bosnių kalba.
        '''</summary>
        Friend ReadOnly Property LanguageCode_bs() As String
            Get
                Return ResourceManager.GetString("LanguageCode_bs", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Katalonų kalba.
        '''</summary>
        Friend ReadOnly Property LanguageCode_ca() As String
            Get
                Return ResourceManager.GetString("LanguageCode_ca", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Čečėnų kalba.
        '''</summary>
        Friend ReadOnly Property LanguageCode_ce() As String
            Get
                Return ResourceManager.GetString("LanguageCode_ce", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Čamorų kalba.
        '''</summary>
        Friend ReadOnly Property LanguageCode_ch() As String
            Get
                Return ResourceManager.GetString("LanguageCode_ch", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Korsikiečių kalba.
        '''</summary>
        Friend ReadOnly Property LanguageCode_co() As String
            Get
                Return ResourceManager.GetString("LanguageCode_co", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Kri kalba.
        '''</summary>
        Friend ReadOnly Property LanguageCode_cr() As String
            Get
                Return ResourceManager.GetString("LanguageCode_cr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Čekų kalba.
        '''</summary>
        Friend ReadOnly Property LanguageCode_cs() As String
            Get
                Return ResourceManager.GetString("LanguageCode_cs", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Bažnytinė slavų kalba.
        '''</summary>
        Friend ReadOnly Property LanguageCode_cu() As String
            Get
                Return ResourceManager.GetString("LanguageCode_cu", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Čiuvašų kalba.
        '''</summary>
        Friend ReadOnly Property LanguageCode_cv() As String
            Get
                Return ResourceManager.GetString("LanguageCode_cv", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Valų kalba.
        '''</summary>
        Friend ReadOnly Property LanguageCode_cy() As String
            Get
                Return ResourceManager.GetString("LanguageCode_cy", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Danų kalba.
        '''</summary>
        Friend ReadOnly Property LanguageCode_da() As String
            Get
                Return ResourceManager.GetString("LanguageCode_da", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Vokiečių kalba.
        '''</summary>
        Friend ReadOnly Property LanguageCode_de() As String
            Get
                Return ResourceManager.GetString("LanguageCode_de", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Maldyviečių kalba.
        '''</summary>
        Friend ReadOnly Property LanguageCode_dv() As String
            Get
                Return ResourceManager.GetString("LanguageCode_dv", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Botijų kalba.
        '''</summary>
        Friend ReadOnly Property LanguageCode_dz() As String
            Get
                Return ResourceManager.GetString("LanguageCode_dz", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Eve kalba.
        '''</summary>
        Friend ReadOnly Property LanguageCode_ee() As String
            Get
                Return ResourceManager.GetString("LanguageCode_ee", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Graikų kalba.
        '''</summary>
        Friend ReadOnly Property LanguageCode_el() As String
            Get
                Return ResourceManager.GetString("LanguageCode_el", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Anglų kalba.
        '''</summary>
        Friend ReadOnly Property LanguageCode_en() As String
            Get
                Return ResourceManager.GetString("LanguageCode_en", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Esperanto.
        '''</summary>
        Friend ReadOnly Property LanguageCode_eo() As String
            Get
                Return ResourceManager.GetString("LanguageCode_eo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ispanų kalba.
        '''</summary>
        Friend ReadOnly Property LanguageCode_es() As String
            Get
                Return ResourceManager.GetString("LanguageCode_es", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Estų kalba.
        '''</summary>
        Friend ReadOnly Property LanguageCode_et() As String
            Get
                Return ResourceManager.GetString("LanguageCode_et", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Baskų kalba.
        '''</summary>
        Friend ReadOnly Property LanguageCode_eu() As String
            Get
                Return ResourceManager.GetString("LanguageCode_eu", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Persų kalba.
        '''</summary>
        Friend ReadOnly Property LanguageCode_fa() As String
            Get
                Return ResourceManager.GetString("LanguageCode_fa", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Fulų kalba.
        '''</summary>
        Friend ReadOnly Property LanguageCode_ff() As String
            Get
                Return ResourceManager.GetString("LanguageCode_ff", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Suomių kalba.
        '''</summary>
        Friend ReadOnly Property LanguageCode_fi() As String
            Get
                Return ResourceManager.GetString("LanguageCode_fi", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Fidžių kalba.
        '''</summary>
        Friend ReadOnly Property LanguageCode_fj() As String
            Get
                Return ResourceManager.GetString("LanguageCode_fj", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Farerų kalba.
        '''</summary>
        Friend ReadOnly Property LanguageCode_fo() As String
            Get
                Return ResourceManager.GetString("LanguageCode_fo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Prancūzų kalba.
        '''</summary>
        Friend ReadOnly Property LanguageCode_fr() As String
            Get
                Return ResourceManager.GetString("LanguageCode_fr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Fryzų kalba.
        '''</summary>
        Friend ReadOnly Property LanguageCode_fy() As String
            Get
                Return ResourceManager.GetString("LanguageCode_fy", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Airių kalba.
        '''</summary>
        Friend ReadOnly Property LanguageCode_ga() As String
            Get
                Return ResourceManager.GetString("LanguageCode_ga", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Škotų gėlų kalba.
        '''</summary>
        Friend ReadOnly Property LanguageCode_gd() As String
            Get
                Return ResourceManager.GetString("LanguageCode_gd", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Galisų kalba.
        '''</summary>
        Friend ReadOnly Property LanguageCode_gl() As String
            Get
                Return ResourceManager.GetString("LanguageCode_gl", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Gvaranių kalba.
        '''</summary>
        Friend ReadOnly Property LanguageCode_gn() As String
            Get
                Return ResourceManager.GetString("LanguageCode_gn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Gudžaratų kalba.
        '''</summary>
        Friend ReadOnly Property LanguageCode_gu() As String
            Get
                Return ResourceManager.GetString("LanguageCode_gu", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Menksiečių kalba.
        '''</summary>
        Friend ReadOnly Property LanguageCode_gv() As String
            Get
                Return ResourceManager.GetString("LanguageCode_gv", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Hausų kalba.
        '''</summary>
        Friend ReadOnly Property LanguageCode_ha() As String
            Get
                Return ResourceManager.GetString("LanguageCode_ha", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Hebrajų kalba.
        '''</summary>
        Friend ReadOnly Property LanguageCode_he() As String
            Get
                Return ResourceManager.GetString("LanguageCode_he", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Hindi.
        '''</summary>
        Friend ReadOnly Property LanguageCode_hi() As String
            Get
                Return ResourceManager.GetString("LanguageCode_hi", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Hiri Motu.
        '''</summary>
        Friend ReadOnly Property LanguageCode_ho() As String
            Get
                Return ResourceManager.GetString("LanguageCode_ho", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Kroatų kalba.
        '''</summary>
        Friend ReadOnly Property LanguageCode_hr() As String
            Get
                Return ResourceManager.GetString("LanguageCode_hr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Haičio kreolų kalba.
        '''</summary>
        Friend ReadOnly Property LanguageCode_ht() As String
            Get
                Return ResourceManager.GetString("LanguageCode_ht", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Vengrų kalba.
        '''</summary>
        Friend ReadOnly Property LanguageCode_hu() As String
            Get
                Return ResourceManager.GetString("LanguageCode_hu", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Armėnų kalba.
        '''</summary>
        Friend ReadOnly Property LanguageCode_hy() As String
            Get
                Return ResourceManager.GetString("LanguageCode_hy", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Herero kalba.
        '''</summary>
        Friend ReadOnly Property LanguageCode_hz() As String
            Get
                Return ResourceManager.GetString("LanguageCode_hz", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Interlingua.
        '''</summary>
        Friend ReadOnly Property LanguageCode_ia() As String
            Get
                Return ResourceManager.GetString("LanguageCode_ia", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Indoneziečių kalba.
        '''</summary>
        Friend ReadOnly Property LanguageCode_id() As String
            Get
                Return ResourceManager.GetString("LanguageCode_id", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Interlingue.
        '''</summary>
        Friend ReadOnly Property LanguageCode_ie() As String
            Get
                Return ResourceManager.GetString("LanguageCode_ie", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Igbų kalba.
        '''</summary>
        Friend ReadOnly Property LanguageCode_ig() As String
            Get
                Return ResourceManager.GetString("LanguageCode_ig", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ji kalba.
        '''</summary>
        Friend ReadOnly Property LanguageCode_ii() As String
            Get
                Return ResourceManager.GetString("LanguageCode_ii", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Inupiakų kalba.
        '''</summary>
        Friend ReadOnly Property LanguageCode_ik() As String
            Get
                Return ResourceManager.GetString("LanguageCode_ik", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ido.
        '''</summary>
        Friend ReadOnly Property LanguageCode_io() As String
            Get
                Return ResourceManager.GetString("LanguageCode_io", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Islandų kalba.
        '''</summary>
        Friend ReadOnly Property LanguageCode_is() As String
            Get
                Return ResourceManager.GetString("LanguageCode_is", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Italų kalba.
        '''</summary>
        Friend ReadOnly Property LanguageCode_it() As String
            Get
                Return ResourceManager.GetString("LanguageCode_it", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Inuktitutas.
        '''</summary>
        Friend ReadOnly Property LanguageCode_iu() As String
            Get
                Return ResourceManager.GetString("LanguageCode_iu", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Japonų kalba.
        '''</summary>
        Friend ReadOnly Property LanguageCode_ja() As String
            Get
                Return ResourceManager.GetString("LanguageCode_ja", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Javiečių kalba.
        '''</summary>
        Friend ReadOnly Property LanguageCode_jv() As String
            Get
                Return ResourceManager.GetString("LanguageCode_jv", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Gruzinų kalba.
        '''</summary>
        Friend ReadOnly Property LanguageCode_ka() As String
            Get
                Return ResourceManager.GetString("LanguageCode_ka", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Kongo kalba.
        '''</summary>
        Friend ReadOnly Property LanguageCode_kg() As String
            Get
                Return ResourceManager.GetString("LanguageCode_kg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Kikujų kalba.
        '''</summary>
        Friend ReadOnly Property LanguageCode_ki() As String
            Get
                Return ResourceManager.GetString("LanguageCode_ki", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Kvanjama kalba.
        '''</summary>
        Friend ReadOnly Property LanguageCode_kj() As String
            Get
                Return ResourceManager.GetString("LanguageCode_kj", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Kazachų kalba.
        '''</summary>
        Friend ReadOnly Property LanguageCode_kk() As String
            Get
                Return ResourceManager.GetString("LanguageCode_kk", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Grenlandų kalba.
        '''</summary>
        Friend ReadOnly Property LanguageCode_kl() As String
            Get
                Return ResourceManager.GetString("LanguageCode_kl", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Kmerų kalba.
        '''</summary>
        Friend ReadOnly Property LanguageCode_km() As String
            Get
                Return ResourceManager.GetString("LanguageCode_km", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Kanadų kalba.
        '''</summary>
        Friend ReadOnly Property LanguageCode_kn() As String
            Get
                Return ResourceManager.GetString("LanguageCode_kn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Korėjiečių kalba.
        '''</summary>
        Friend ReadOnly Property LanguageCode_ko() As String
            Get
                Return ResourceManager.GetString("LanguageCode_ko", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Kanurių kalba.
        '''</summary>
        Friend ReadOnly Property LanguageCode_kr() As String
            Get
                Return ResourceManager.GetString("LanguageCode_kr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Kašmyriečių kalba.
        '''</summary>
        Friend ReadOnly Property LanguageCode_ks() As String
            Get
                Return ResourceManager.GetString("LanguageCode_ks", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Kurdų kalba.
        '''</summary>
        Friend ReadOnly Property LanguageCode_ku() As String
            Get
                Return ResourceManager.GetString("LanguageCode_ku", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Komių kalba.
        '''</summary>
        Friend ReadOnly Property LanguageCode_kv() As String
            Get
                Return ResourceManager.GetString("LanguageCode_kv", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Kornų kalba.
        '''</summary>
        Friend ReadOnly Property LanguageCode_kw() As String
            Get
                Return ResourceManager.GetString("LanguageCode_kw", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Kirgizų kalba.
        '''</summary>
        Friend ReadOnly Property LanguageCode_ky() As String
            Get
                Return ResourceManager.GetString("LanguageCode_ky", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Lotynų kalba.
        '''</summary>
        Friend ReadOnly Property LanguageCode_la() As String
            Get
                Return ResourceManager.GetString("LanguageCode_la", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Liuksemburgiečių kalba.
        '''</summary>
        Friend ReadOnly Property LanguageCode_lb() As String
            Get
                Return ResourceManager.GetString("LanguageCode_lb", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Lugandų kalba.
        '''</summary>
        Friend ReadOnly Property LanguageCode_lg() As String
            Get
                Return ResourceManager.GetString("LanguageCode_lg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Limburgieičių kalba.
        '''</summary>
        Friend ReadOnly Property LanguageCode_li() As String
            Get
                Return ResourceManager.GetString("LanguageCode_li", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Lingalų kalba.
        '''</summary>
        Friend ReadOnly Property LanguageCode_ln() As String
            Get
                Return ResourceManager.GetString("LanguageCode_ln", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Lao kalba.
        '''</summary>
        Friend ReadOnly Property LanguageCode_lo() As String
            Get
                Return ResourceManager.GetString("LanguageCode_lo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Lietuvių kalba.
        '''</summary>
        Friend ReadOnly Property LanguageCode_lt() As String
            Get
                Return ResourceManager.GetString("LanguageCode_lt", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Lubų kalba.
        '''</summary>
        Friend ReadOnly Property LanguageCode_lu() As String
            Get
                Return ResourceManager.GetString("LanguageCode_lu", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Latvių kalba.
        '''</summary>
        Friend ReadOnly Property LanguageCode_lv() As String
            Get
                Return ResourceManager.GetString("LanguageCode_lv", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Malagasių kalba.
        '''</summary>
        Friend ReadOnly Property LanguageCode_mg() As String
            Get
                Return ResourceManager.GetString("LanguageCode_mg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Maršaliečių kalba.
        '''</summary>
        Friend ReadOnly Property LanguageCode_mh() As String
            Get
                Return ResourceManager.GetString("LanguageCode_mh", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Maorių kalba.
        '''</summary>
        Friend ReadOnly Property LanguageCode_mi() As String
            Get
                Return ResourceManager.GetString("LanguageCode_mi", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Makedonų kalba.
        '''</summary>
        Friend ReadOnly Property LanguageCode_mk() As String
            Get
                Return ResourceManager.GetString("LanguageCode_mk", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Malajalių kalba.
        '''</summary>
        Friend ReadOnly Property LanguageCode_ml() As String
            Get
                Return ResourceManager.GetString("LanguageCode_ml", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Mongolų kalba.
        '''</summary>
        Friend ReadOnly Property LanguageCode_mn() As String
            Get
                Return ResourceManager.GetString("LanguageCode_mn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Maratų kalba.
        '''</summary>
        Friend ReadOnly Property LanguageCode_mr() As String
            Get
                Return ResourceManager.GetString("LanguageCode_mr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Malajų kalba.
        '''</summary>
        Friend ReadOnly Property LanguageCode_ms() As String
            Get
                Return ResourceManager.GetString("LanguageCode_ms", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Maltiečių kalba.
        '''</summary>
        Friend ReadOnly Property LanguageCode_mt() As String
            Get
                Return ResourceManager.GetString("LanguageCode_mt", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Mjanmų kalba.
        '''</summary>
        Friend ReadOnly Property LanguageCode_my() As String
            Get
                Return ResourceManager.GetString("LanguageCode_my", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Nauriečių kalba.
        '''</summary>
        Friend ReadOnly Property LanguageCode_na() As String
            Get
                Return ResourceManager.GetString("LanguageCode_na", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Norvegų kalba bokmål.
        '''</summary>
        Friend ReadOnly Property LanguageCode_nb() As String
            Get
                Return ResourceManager.GetString("LanguageCode_nb", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Šiaurės ndebelų kalba.
        '''</summary>
        Friend ReadOnly Property LanguageCode_nd() As String
            Get
                Return ResourceManager.GetString("LanguageCode_nd", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Nepalų kalba.
        '''</summary>
        Friend ReadOnly Property LanguageCode_ne() As String
            Get
                Return ResourceManager.GetString("LanguageCode_ne", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ndongų kalba.
        '''</summary>
        Friend ReadOnly Property LanguageCode_ng() As String
            Get
                Return ResourceManager.GetString("LanguageCode_ng", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Olandų kalba.
        '''</summary>
        Friend ReadOnly Property LanguageCode_nl() As String
            Get
                Return ResourceManager.GetString("LanguageCode_nl", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Naujoji norvegų kalba Nynorsk.
        '''</summary>
        Friend ReadOnly Property LanguageCode_nn() As String
            Get
                Return ResourceManager.GetString("LanguageCode_nn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Norvegų kalba.
        '''</summary>
        Friend ReadOnly Property LanguageCode_no() As String
            Get
                Return ResourceManager.GetString("LanguageCode_no", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Pietų ndebelų kalba.
        '''</summary>
        Friend ReadOnly Property LanguageCode_nr() As String
            Get
                Return ResourceManager.GetString("LanguageCode_nr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Navachų kalba.
        '''</summary>
        Friend ReadOnly Property LanguageCode_nv() As String
            Get
                Return ResourceManager.GetString("LanguageCode_nv", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Čičevų kalba.
        '''</summary>
        Friend ReadOnly Property LanguageCode_ny() As String
            Get
                Return ResourceManager.GetString("LanguageCode_ny", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Oksitanų kalba.
        '''</summary>
        Friend ReadOnly Property LanguageCode_oc() As String
            Get
                Return ResourceManager.GetString("LanguageCode_oc", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Odžibvių kalba.
        '''</summary>
        Friend ReadOnly Property LanguageCode_oj() As String
            Get
                Return ResourceManager.GetString("LanguageCode_oj", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Oromų kalba.
        '''</summary>
        Friend ReadOnly Property LanguageCode_om() As String
            Get
                Return ResourceManager.GetString("LanguageCode_om", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Orijų kalba.
        '''</summary>
        Friend ReadOnly Property LanguageCode_or() As String
            Get
                Return ResourceManager.GetString("LanguageCode_or", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Osetinų kalba.
        '''</summary>
        Friend ReadOnly Property LanguageCode_os() As String
            Get
                Return ResourceManager.GetString("LanguageCode_os", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Pendžabų kalba.
        '''</summary>
        Friend ReadOnly Property LanguageCode_pa() As String
            Get
                Return ResourceManager.GetString("LanguageCode_pa", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Pali kalba.
        '''</summary>
        Friend ReadOnly Property LanguageCode_pi() As String
            Get
                Return ResourceManager.GetString("LanguageCode_pi", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Lenkų kalba.
        '''</summary>
        Friend ReadOnly Property LanguageCode_pl() As String
            Get
                Return ResourceManager.GetString("LanguageCode_pl", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Puštūnų kalba.
        '''</summary>
        Friend ReadOnly Property LanguageCode_ps() As String
            Get
                Return ResourceManager.GetString("LanguageCode_ps", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Portugalų kalba.
        '''</summary>
        Friend ReadOnly Property LanguageCode_pt() As String
            Get
                Return ResourceManager.GetString("LanguageCode_pt", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Kečujų kalba.
        '''</summary>
        Friend ReadOnly Property LanguageCode_qu() As String
            Get
                Return ResourceManager.GetString("LanguageCode_qu", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Retoromanų kalba.
        '''</summary>
        Friend ReadOnly Property LanguageCode_rm() As String
            Get
                Return ResourceManager.GetString("LanguageCode_rm", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Kirundžių kalba.
        '''</summary>
        Friend ReadOnly Property LanguageCode_rn() As String
            Get
                Return ResourceManager.GetString("LanguageCode_rn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Rumunų kalba.
        '''</summary>
        Friend ReadOnly Property LanguageCode_ro() As String
            Get
                Return ResourceManager.GetString("LanguageCode_ro", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Rusų kalba.
        '''</summary>
        Friend ReadOnly Property LanguageCode_ru() As String
            Get
                Return ResourceManager.GetString("LanguageCode_ru", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Kinjaruanda.
        '''</summary>
        Friend ReadOnly Property LanguageCode_rw() As String
            Get
                Return ResourceManager.GetString("LanguageCode_rw", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sanskritas.
        '''</summary>
        Friend ReadOnly Property LanguageCode_sa() As String
            Get
                Return ResourceManager.GetString("LanguageCode_sa", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sardų kalba.
        '''</summary>
        Friend ReadOnly Property LanguageCode_sc() As String
            Get
                Return ResourceManager.GetString("LanguageCode_sc", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sindžų kalba.
        '''</summary>
        Friend ReadOnly Property LanguageCode_sd() As String
            Get
                Return ResourceManager.GetString("LanguageCode_sd", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Šiaurės samių kalba.
        '''</summary>
        Friend ReadOnly Property LanguageCode_se() As String
            Get
                Return ResourceManager.GetString("LanguageCode_se", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sangų kalba.
        '''</summary>
        Friend ReadOnly Property LanguageCode_sg() As String
            Get
                Return ResourceManager.GetString("LanguageCode_sg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Serbų kroatų kalba.
        '''</summary>
        Friend ReadOnly Property LanguageCode_sh() As String
            Get
                Return ResourceManager.GetString("LanguageCode_sh", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sinhalų kalba.
        '''</summary>
        Friend ReadOnly Property LanguageCode_si() As String
            Get
                Return ResourceManager.GetString("LanguageCode_si", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Slovakų kalba.
        '''</summary>
        Friend ReadOnly Property LanguageCode_sk() As String
            Get
                Return ResourceManager.GetString("LanguageCode_sk", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Slovėnų kalba.
        '''</summary>
        Friend ReadOnly Property LanguageCode_sl() As String
            Get
                Return ResourceManager.GetString("LanguageCode_sl", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Samoa kalba.
        '''</summary>
        Friend ReadOnly Property LanguageCode_sm() As String
            Get
                Return ResourceManager.GetString("LanguageCode_sm", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Šonų kalba.
        '''</summary>
        Friend ReadOnly Property LanguageCode_sn() As String
            Get
                Return ResourceManager.GetString("LanguageCode_sn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Somalių kalba.
        '''</summary>
        Friend ReadOnly Property LanguageCode_so() As String
            Get
                Return ResourceManager.GetString("LanguageCode_so", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Albanų kalba.
        '''</summary>
        Friend ReadOnly Property LanguageCode_sq() As String
            Get
                Return ResourceManager.GetString("LanguageCode_sq", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Serbų kalba.
        '''</summary>
        Friend ReadOnly Property LanguageCode_sr() As String
            Get
                Return ResourceManager.GetString("LanguageCode_sr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Svazių kalba.
        '''</summary>
        Friend ReadOnly Property LanguageCode_ss() As String
            Get
                Return ResourceManager.GetString("LanguageCode_ss", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Pietų sotų kalba.
        '''</summary>
        Friend ReadOnly Property LanguageCode_st() As String
            Get
                Return ResourceManager.GetString("LanguageCode_st", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sundų kalba.
        '''</summary>
        Friend ReadOnly Property LanguageCode_su() As String
            Get
                Return ResourceManager.GetString("LanguageCode_su", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Švedų kalba.
        '''</summary>
        Friend ReadOnly Property LanguageCode_sv() As String
            Get
                Return ResourceManager.GetString("LanguageCode_sv", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Suahilių kalba.
        '''</summary>
        Friend ReadOnly Property LanguageCode_sw() As String
            Get
                Return ResourceManager.GetString("LanguageCode_sw", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tamilų kalba.
        '''</summary>
        Friend ReadOnly Property LanguageCode_ta() As String
            Get
                Return ResourceManager.GetString("LanguageCode_ta", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Telugų kalba.
        '''</summary>
        Friend ReadOnly Property LanguageCode_te() As String
            Get
                Return ResourceManager.GetString("LanguageCode_te", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tadžikų kalba.
        '''</summary>
        Friend ReadOnly Property LanguageCode_tg() As String
            Get
                Return ResourceManager.GetString("LanguageCode_tg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tajų kalba.
        '''</summary>
        Friend ReadOnly Property LanguageCode_th() As String
            Get
                Return ResourceManager.GetString("LanguageCode_th", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tigrinijų kalba.
        '''</summary>
        Friend ReadOnly Property LanguageCode_ti() As String
            Get
                Return ResourceManager.GetString("LanguageCode_ti", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Turkmėnų kalba.
        '''</summary>
        Friend ReadOnly Property LanguageCode_tk() As String
            Get
                Return ResourceManager.GetString("LanguageCode_tk", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tagalų kalba.
        '''</summary>
        Friend ReadOnly Property LanguageCode_tl() As String
            Get
                Return ResourceManager.GetString("LanguageCode_tl", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tsvanų kalba.
        '''</summary>
        Friend ReadOnly Property LanguageCode_tn() As String
            Get
                Return ResourceManager.GetString("LanguageCode_tn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tongos kalba.
        '''</summary>
        Friend ReadOnly Property LanguageCode_to() As String
            Get
                Return ResourceManager.GetString("LanguageCode_to", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Turkų kalba.
        '''</summary>
        Friend ReadOnly Property LanguageCode_tr() As String
            Get
                Return ResourceManager.GetString("LanguageCode_tr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tsongų kalba.
        '''</summary>
        Friend ReadOnly Property LanguageCode_ts() As String
            Get
                Return ResourceManager.GetString("LanguageCode_ts", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Totorių kalba.
        '''</summary>
        Friend ReadOnly Property LanguageCode_tt() As String
            Get
                Return ResourceManager.GetString("LanguageCode_tt", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tvi kalba.
        '''</summary>
        Friend ReadOnly Property LanguageCode_tw() As String
            Get
                Return ResourceManager.GetString("LanguageCode_tw", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Taitiečių kalba.
        '''</summary>
        Friend ReadOnly Property LanguageCode_ty() As String
            Get
                Return ResourceManager.GetString("LanguageCode_ty", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Uigūrų kalba.
        '''</summary>
        Friend ReadOnly Property LanguageCode_ug() As String
            Get
                Return ResourceManager.GetString("LanguageCode_ug", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ukrainiečių kalba.
        '''</summary>
        Friend ReadOnly Property LanguageCode_uk() As String
            Get
                Return ResourceManager.GetString("LanguageCode_uk", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Urdu.
        '''</summary>
        Friend ReadOnly Property LanguageCode_ur() As String
            Get
                Return ResourceManager.GetString("LanguageCode_ur", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Uzbekų kalba.
        '''</summary>
        Friend ReadOnly Property LanguageCode_uz() As String
            Get
                Return ResourceManager.GetString("LanguageCode_uz", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Vendų kalba.
        '''</summary>
        Friend ReadOnly Property LanguageCode_ve() As String
            Get
                Return ResourceManager.GetString("LanguageCode_ve", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Vietnamiečių kalba.
        '''</summary>
        Friend ReadOnly Property LanguageCode_vi() As String
            Get
                Return ResourceManager.GetString("LanguageCode_vi", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Volapiukas.
        '''</summary>
        Friend ReadOnly Property LanguageCode_vo() As String
            Get
                Return ResourceManager.GetString("LanguageCode_vo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Valonų kalba.
        '''</summary>
        Friend ReadOnly Property LanguageCode_wa() As String
            Get
                Return ResourceManager.GetString("LanguageCode_wa", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Volofų kalba.
        '''</summary>
        Friend ReadOnly Property LanguageCode_wo() As String
            Get
                Return ResourceManager.GetString("LanguageCode_wo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Kosų kalba.
        '''</summary>
        Friend ReadOnly Property LanguageCode_xh() As String
            Get
                Return ResourceManager.GetString("LanguageCode_xh", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Jidiš.
        '''</summary>
        Friend ReadOnly Property LanguageCode_yi() As String
            Get
                Return ResourceManager.GetString("LanguageCode_yi", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Jorubų kalba.
        '''</summary>
        Friend ReadOnly Property LanguageCode_yo() As String
            Get
                Return ResourceManager.GetString("LanguageCode_yo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Džuangų kalba.
        '''</summary>
        Friend ReadOnly Property LanguageCode_za() As String
            Get
                Return ResourceManager.GetString("LanguageCode_za", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Kinų kalba (supaprastinta).
        '''</summary>
        Friend ReadOnly Property LanguageCode_zh_cn() As String
            Get
                Return ResourceManager.GetString("LanguageCode_zh_cn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Kinų kalba (tradicinė).
        '''</summary>
        Friend ReadOnly Property LanguageCode_zh_tw() As String
            Get
                Return ResourceManager.GetString("LanguageCode_zh_tw", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Zulų kalba.
        '''</summary>
        Friend ReadOnly Property LanguageCode_zu() As String
            Get
                Return ResourceManager.GetString("LanguageCode_zu", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
